[package]
name = "libsys"
version = "0.3.2"
edition = "2024"

[dependencies]
num_enum = { version = "0.7", default-features = false }
spin = { version = "*", default-features = false, features = ["once"] }
thiserror = { version = "*", default-features = false }
