[package]
name = "libsys"
version = "0.1.3"
edition = "2024"

[dependencies]
log = { version = "0.4", default-features = false }
num_enum = { version = "0.7", default-features = false }
uuid = { version = "1.3", default-features = false }
thiserror = { version = "*", default-features = false }
